coverage:
  precision: 2
  round: down
  range: "76...100"
  status:
    project:
      default:
        target: 76%
        threshold: 0.25%
      elixir:
        target: 76%
        threshold: 0.25%
        flags:
          - elixir
    patch:
      default:
        target: 90%
        threshold: 0%

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 0.25%
      - type: patch
        target: 90%
  individual_components:
    - component_id: elixir-core
      name: Elixir core
      paths:
        - "lib/**"
      flag_regexes:
        - "elixir"
comment:
  layout: "reach,diff,flags,components,files"
  require_changes: true
