expected_version = "0.0.3"
actual_version = Application.spec(:twelvgaige, :vsn) |> to_string()

if actual_version != expected_version do
  raise "fixture must be generated by Twelvgaige #{expected_version}, got #{actual_version}"
end

output =
  case System.argv() do
    [path] -> Path.expand(path)
    _other -> raise "usage: mix run generate.exs OUTPUT.sqlite3"
  end

if File.exists?(output) do
  raise "refusing to overwrite existing fixture: #{output}"
end

File.mkdir_p!(Path.dirname(output))

{store_module, name} =
  case System.get_env("TWELVGAIGE_MIGRATION_FIXTURE_STORE", "sqlite") do
    "sqlite" ->
      {Twelvgaige.Store.SQLite, :previous_release_sqlite_migration_fixture}

    "file" ->
      {Twelvgaige.Store.File, :previous_release_file_migration_fixture}

    other ->
      raise "unsupported fixture store: #{other}"
  end

{:ok, store} = store_module.start_link(name: name, path: output)

complete =
  Twelvgaige.Round.Snapshot.new(%{
    id: "previous_complete",
    shell_id: "migration-fixture",
    shell_version: "1.0.0",
    status: :firing,
    version: 0,
    input: %{"objective" => "verify completed work remains readable"},
    shots: [%{id: "complete-shot", kind: :slug, status: :running, attempt: 1}]
  })

complete_manifest = %{
  round_id: complete.id,
  shell_id: complete.shell_id,
  shell_version: complete.shell_version,
  workflow: %{"id" => complete.shell_id, "version" => complete.shell_version}
}

:ok =
  GenServer.call(
    name,
    {:create_round, complete, complete_manifest,
     [%{event_type: :round_created, round_id: complete.id, actor: "fixture"}]}
  )

completed = %{
  complete
  | status: :complete,
    shots: [
      Twelvgaige.Shot.State.new(%{
        id: "complete-shot",
        kind: :slug,
        status: :complete,
        attempt: 1,
        output: %{"result" => "preserved"}
      })
    ]
}

:ok =
  GenServer.call(
    name,
    {:commit_transition, complete.id, 0, "previous-complete-transition", completed,
     [%{event_type: :round_completed}],
     [%{event_type: :round_completed, round_id: complete.id, actor: "fixture"}]}
  )

interrupted =
  Twelvgaige.Round.Snapshot.new(%{
    id: "previous_interrupted",
    shell_id: "migration-fixture",
    shell_version: "1.0.0",
    status: :firing,
    version: 1,
    input: %{"objective" => "require conservative restart reconciliation"},
    shots: [
      %{
        id: "interrupted-shot",
        kind: :slug,
        status: :running,
        attempt: 1,
        started_at: ~U[2026-08-01 12:00:00Z]
      }
    ]
  })

interrupted_manifest = %{
  round_id: interrupted.id,
  shell_id: interrupted.shell_id,
  shell_version: interrupted.shell_version,
  workflow: %{"id" => interrupted.shell_id, "version" => interrupted.shell_version}
}

:ok =
  GenServer.call(
    name,
    {:create_round, interrupted, interrupted_manifest,
     [%{event_type: :round_created, round_id: interrupted.id, actor: "fixture"}]}
  )

:ok =
  GenServer.call(
    name,
    {:record_attempt_started,
     %{
       round_id: interrupted.id,
       shot_id: "interrupted-shot",
       attempt: 1,
       status: :started
     }, []}
  )

:ok =
  GenServer.call(
    name,
    {:record_tool_intent,
     %{
       round_id: interrupted.id,
       shot_id: "interrupted-shot",
       attempt: 1,
       id: "unresolved-write",
       status: :intent_recorded,
       safety_level: :write,
       input: %{"path" => "result.txt"}
     }, []}
  )

GenServer.stop(store)

digest = output |> File.read!() |> then(&:crypto.hash(:sha256, &1)) |> Base.encode16(case: :lower)
IO.puts("generated #{output} sha256:#{digest}")
